version: '3'

services:
  grafana:
    image: grafana/grafana
    #    restart: unless-stopped
    container_name: grafana
    network_mode: "host"
    volumes:
      - /mnt/d/self/d2c/d2c-payment-service/docker/data/grafana_data:/var/lib/grafana        # Persist data
      - /mnt/d/self/d2c/d2c-payment-service/docker/data/grafana_config:/etc/grafana          # External configuration
      - /mnt/d/self/d2c/d2c-payment-service/docker/data/grafana_plugins:/var/lib/grafana/plugins  # Plugins
      - /mnt/d/self/d2c/d2c-payment-service/docker/data/grafana_logs:/var/log/grafana        # Access logs
    env_file:
      - ./docker/grafana.env

networks:
  my_shared_network:
    external: true