# parent-project/docker-compose.yml
version: '3'

services:
  d2c-payment-service:
    extends:
      file: d2c-payment-service/docker-compose.yml
      service: d2c-payment-service
  d2c-notification-service:
    extends:
      file: d2c-notification-service/docker-compose.yml
      service: d2c-notification-service
  prometheus:
    extends:
      file: d2c-payment-service/docker-compose.yml
      service: prometheus
  grafana:
    extends:
      file: d2c-payment-service/docker-compose.yml
      service: grafana

networks:
  my_shared_network:
    driver: bridge
