version: '3'

services:
  # Spring Boot Application
  spring-boot-app:
#    extends:
#      file: ../docker-compose.yml
#      service: common-service
    image: gradle:8.10-jdk17  # Gradle image with Java 17
    container_name: d2c-notification-service-app
    working_dir: /app
    volumes:
      - .:/app               # Mount project root into container
    ports:
      - "9083:9083"
    command: ./gradlew bootRun  # Command to run the Spring Boot app
    stdin_open: true
    tty: true
    networks:
      - my_shared_network
    environment:
      - SERVICE_NAME=d2c-notification-service

networks:
  my_shared_network:
    external: true